fritzbox:
  url: http://fritz.box
  user: admin
  password: "xxx"
  deviceConfigs:
    -
      name: "FRITZ!DECT 200 #1"
      standbyInWatt: 10
      waitInSeconds: 600
      startMessage: "Washingmachine running."
      stopMessage: "Washingmachine ready. Costs: {COST}, Consumption: {WH}."
      pricePerKwh: 0.28025
telegram:
  token: xxx
  botUsername: botusername
  allowedNumbers:
    - +49xxx
intervalInMS: 2000
logging:
  level.de.veltrus.gotShitDone.telegram.KnownChatIds: debug
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  url: jdbc:h2:./h2.database
  username: sa
  password:
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect